version = 1
SPDX-PackageName = "repository-template"
SPDX-PackageSupplier = "open-component-model-maintainers@lists.neonephos.org"
SPDX-PackageDownloadLocation = "https://ocm.software/repository-template"
